#

x-environment-mongo:
    &environment-mongo
    - TERM=xterm
    - MONGO_INITDB_ROOT_USERNAME=mongo_user
    - MONGO_INITDB_ROOT_PASSWORD=mongo_pw
    - MONGO_INITDB_DATABASE=admin
    - APP_NAME=mongodb-data
    - APP_TYPE=mongodb-data
    - GLIBC_TUNABLES=glibc.pthread.rseq=0

x-configs-mongo:
  &configs-mongo
  - source: mongodb-config
    target: /conf/mongo.conf
    mode: 0644

services:
  web:
    image: service_slim
    ports:
      - "5000:5000"
    depends_on:
      - mongodb-data
    environment:
      - FLASK_ENV=development
    labels:
      kompose.service.type: LoadBalancer
    #annotations:
    #  kompose.service.expose: "true"
    #  kompose.service.port: "80"
    #  kompose.service.targetPort: "5000"
    #spec:
    #  type: LoadBalancer
    #  ports:
    #    - protocol: TCP
    #      port: 80
    #      targetPort: 5000
    #  selector:
    #    io.kompose.service: web

  mongodb-data:
    image: mongo:8.0.4
    command: mongod --port 27017 --config /conf/mongo.conf
    ports:
      - "27017:27017"
    #volumes: *volumes-mongo
    environment: *environment-mongo
    configs: *configs-mongo
    deploy:
      replicas: 1
    #logging:
    #  driver: gelf
    #  options:
    #    gelf-address: udp://${GRAYLOG_PEER}:12201
    #    tag: "database"
    #    env: "APP_ID,APP_ENV,APP_NAME,APP_TYPE,APP_LOCATION"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - default
        
volumes:
  mongodata:
  shared:
    external: true

configs:
  mongodb-config:
    file: ./configs/mongo.conf