name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set the OWNER_LC environment variable to the lowercase owner name
    - name: Set lower case owner name
      run: |
        echo "OWNER_LC=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ env.OWNER_LC }}/service_slim:latest .

    # Push the Docker image to GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ env.OWNER_LC }}/service_slim:latest