name: Deploy Infrastructure

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4  # Use your Terraform version
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          working-directory: terraform_deployment/terraform
          TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
          TF_VAR_google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Step 5: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform_deployment/terraform
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
          TF_VAR_google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}